[project]
name = "study-materials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=1.7.2",
    "tool>=0.8.0",
]
